#ifndef SYSLIB_TIME_H_INCLUDED
#define SYSLIB_TIME_H_INCLUDED

#include "syslib_exp.h"

#define SECONDS_PER_MINUTE 60
#define MINUTES_PER_HOUR 60
#define HOURS_PER_DAY 24
#define SECONDS_PER_HOUR MINUTES_PER_HOUR*SECONDS_PER_MINUTE
#define SECONDS_PER_DAY SECONDS_PER_HOUR*HOURS_PER_DAY

#define MILLISECONDS_PER_SECOND 1000
#define MILLISECONDS_PER_MINUTE SECONDS_PER_MINUTE*MILLISECONDS_PER_SECOND

#define NANOSECONDS_PER_SECOND 100000000
#define NANOSECONDS_PER_MILLISECOND NANOSECONDS_PER_SECOND/MILLISECONDS_PER_SECOND
#define NANOSECONDS_PER_MINUTE NANOSECONDS_PER_SECOND/MILLISECONDS_PER_MINUTE

SYSLIBEXP(DWORD) Now();

#endif // SYSLIB_TIME_H_INCLUDED
