#ifndef WAITFORMULTIPLEOBJECTS_H_INCLUDED
#define WAITFORMULTIPLEOBJECTS_H_INCLUDED

typedef struct _WAIT_FOR_MULTIPLE_OBJECTS_THREAD
{
    HANDLE hStopEvent;

    DWORD dwPosition;

    DWORD nCount;
    HANDLE Handles[MAXIMUM_WAIT_OBJECTS];
    BOOL bWaitAll;
    DWORD dwMilliseconds;

    DWORD dwRet;
} WAIT_FOR_MULTIPLE_OBJECTS_THREAD, *PWAIT_FOR_MULTIPLE_OBJECTS_THREAD;

#endif // WAITFORMULTIPLEOBJECTS_H_INCLUDED
