#ifndef THREADGROUP_H_INCLUDED
#define THREADGROUP_H_INCLUDED

struct THREADS_GROUP
{
    DWORD dwCount;
    SAFE_CRITICAL_SECTION csGroup;
    HANDLE hThreads[MAXIMUM_WAIT_OBJECTS];
};

#endif // THREADGROUP_H_INCLUDED
